// packages/solid/src/dialog/primitive.tsx
/** @jsxImportSource @opentui/solid */

import {
  extend,
  Portal as SolidPortal,
  spread,
  useRenderer,
} from "@opentui/solid";
import type { DialogPrimitiveState } from "@opentui-ui/core/dialog";
import {
  type DialogBackdropOptions,
  DialogBackdropRenderable,
  type DialogCloseOptions,
  DialogCloseRenderable,
  type DialogDescriptionOptions,
  DialogDescriptionRenderable,
  type DialogPopupOptions,
  DialogPopupRenderable,
  type DialogPortalOptions,
  DialogPortalRenderable,
  type DialogRootOptions,
  DialogRootRenderable,
  DialogStore,
  type DialogTitleOptions,
  DialogTitleRenderable,
  type DialogTriggerOptions,
  DialogTriggerRenderable,
} from "@opentui-ui/core/dialog";
import {
  createComponent,
  createContext,
  createEffect,
  createSignal,
  type JSX,
  onCleanup,
  onMount,
  type Ref,
  splitProps,
  untrack,
  useContext,
} from "solid-js";

const tags = {
  root: "otui-dialog-primitive-root",
  trigger: "otui-dialog-primitive-trigger",
  backdrop: "otui-dialog-primitive-backdrop",
  popup: "otui-dialog-primitive-popup",
  title: "otui-dialog-primitive-title",
  description: "otui-dialog-primitive-description",
  close: "otui-dialog-primitive-close",
} as const;
extend({
  [tags.root]: DialogRootRenderable,
  [tags.trigger]: DialogTriggerRenderable,
  [tags.backdrop]: DialogBackdropRenderable,
  [tags.popup]: DialogPopupRenderable,
  [tags.title]: DialogTitleRenderable,
  [tags.description]: DialogDescriptionRenderable,
  [tags.close]: DialogCloseRenderable,
});
const StoreContext = createContext<DialogStore>();
export type DialogRootProps = Omit<DialogRootOptions, "store"> & {
  children?: JSX.Element | ((state: DialogPrimitiveState) => JSX.Element);
  ref?: Ref<DialogRootRenderable>;
};
export type DialogTriggerProps = Omit<DialogTriggerOptions, "store"> & {
  children?: JSX.Element;
  ref?: Ref<DialogTriggerRenderable>;
};
export type DialogPortalProps = Omit<DialogPortalOptions, "store"> & {
  children?: JSX.Element;
  ref?: Ref<DialogPortalRenderable>;
};
export type DialogBackdropProps = Omit<DialogBackdropOptions, "store"> & {
  children?: JSX.Element;
  ref?: Ref<DialogBackdropRenderable>;
};
export type DialogPopupProps = Omit<DialogPopupOptions, "store"> & {
  children?: JSX.Element;
  ref?: Ref<DialogPopupRenderable>;
};
export type DialogTitleProps = Omit<DialogTitleOptions, "store"> & {
  children?: JSX.Element;
  ref?: Ref<DialogTitleRenderable>;
};
export type DialogDescriptionProps = Omit<DialogDescriptionOptions, "store"> & {
  children?: JSX.Element;
  ref?: Ref<DialogDescriptionRenderable>;
};
export type DialogCloseProps = Omit<DialogCloseOptions, "store"> & {
  children?: JSX.Element;
  ref?: Ref<DialogCloseRenderable>;
};

function setRef<T>(ref: Ref<T> | undefined, value: T): void {
  if (typeof ref === "function") (ref as (value: T) => void)(value);
}
function spreadProps<T extends object>(
  element: Parameters<typeof spread>[0],
  getProps: () => T,
): void {
  let previous: string[] = [];
  spread(element, () => {
    const next = getProps() as Record<string, unknown>;
    const removed = Object.fromEntries(
      previous
        .filter((key) => !Object.hasOwn(next, key))
        .map((key) => [key, undefined]),
    );
    previous = Object.keys(next);
    return { ...removed, ...next };
  });
}
function useStore(name: string): DialogStore {
  const store = useContext(StoreContext);
  if (!store)
    throw new Error(
      `DialogPrimitive.${name} must be rendered inside DialogPrimitive.Root`,
    );
  return store;
}

function Root(props: DialogRootProps): JSX.Element {
  const renderer = useRenderer();
  const store = new DialogStore(
    renderer,
    untrack(() => props),
  );
  const [state, setState] = createSignal(store.state);
  const publicState: DialogPrimitiveState = {
    get open() {
      return state().open;
    },
  };
  const [local, initial] = splitProps(props, [
    "children",
    "open",
    "onOpenChange",
    "ref",
  ]);
  const element = new DialogRootRenderable(
    renderer,
    untrack(() => ({ ...initial, store })),
  );
  createEffect(() => {
    element.open = local.open;
    element.onOpenChange = local.onOpenChange;
  });
  onCleanup(() => {
    store.destroy();
    if (!element.isDestroyed) element.destroy();
  });
  onCleanup(store.subscribe(setState));
  setRef(local.ref, element);
  return createComponent(StoreContext.Provider, {
    value: store,
    get children() {
      const child = local.children;
      const content = typeof child === "function" ? child(publicState) : child;
      spreadProps(element, () => ({ ...initial, children: content }));
      return element;
    },
  });
}
function Trigger(props: DialogTriggerProps): JSX.Element {
  const store = useStore("Trigger");
  const [local, initial] = splitProps(props, ["ref"]);
  const renderer = useRenderer();
  const element = new DialogTriggerRenderable(
    renderer,
    untrack(() => ({ ...initial, store })),
  );
  setRef(local.ref, element);
  spreadProps(element, () => ({ ...initial }));
  return element;
}
function Portal(props: DialogPortalProps): JSX.Element {
  const renderer = useRenderer();
  const store = useStore("Portal");
  const [local, initial] = splitProps(props, ["children", "ref"]);
  const portal = new DialogPortalRenderable(
    renderer,
    untrack(() => ({ ...initial, store })),
  );
  renderer.root.add(portal);
  setRef(local.ref, portal);
  spreadProps(portal, () => ({ ...initial }));
  onCleanup(() => {
    if (!portal.isDestroyed) {
      renderer.root.remove(portal);
      portal.destroyRecursively();
    }
  });
  return createComponent(SolidPortal, {
    mount: portal,
    get children() {
      return local.children;
    },
  });
}
function Backdrop(props: DialogBackdropProps): JSX.Element {
  const store = useStore("Backdrop");
  const renderer = useRenderer();
  const [local, initial] = splitProps(props, ["ref"]);
  const element = new DialogBackdropRenderable(
    renderer,
    untrack(() => ({ ...initial, store })),
  );
  setRef(local.ref, element);
  spreadProps(element, () => ({ ...initial }));
  return element;
}
function Popup(props: DialogPopupProps): JSX.Element {
  const store = useStore("Popup");
  const renderer = useRenderer();
  const [local, initial] = splitProps(props, ["children", "ref"]);
  const element = new DialogPopupRenderable(
    renderer,
    untrack(() => ({ ...initial, store })),
  );
  setRef(local.ref, element);
  spreadProps(element, () => ({ ...initial, children: local.children }));
  return element;
}
function TextPart(
  props: (DialogTitleProps | DialogDescriptionProps) & {
    tag: string;
    store: DialogStore;
  },
): JSX.Element {
  const { tag, store, ...rest } = props;
  const renderer = useRenderer();
  const [local, initial] = splitProps(rest, ["ref"]);
  const element =
    tag === tags.title
      ? new DialogTitleRenderable(
          renderer,
          untrack(() => ({ ...initial, store })),
        )
      : new DialogDescriptionRenderable(
          renderer,
          untrack(() => ({ ...initial, store })),
        );
  setRef(local.ref, element);
  spreadProps(element, () => ({ ...initial }));
  return element;
}
function Title(props: DialogTitleProps): JSX.Element {
  return TextPart({ ...props, tag: tags.title, store: useStore("Title") });
}
function Description(props: DialogDescriptionProps): JSX.Element {
  return TextPart({
    ...props,
    tag: tags.description,
    store: useStore("Description"),
  });
}
function Close(props: DialogCloseProps): JSX.Element {
  const store = useStore("Close");
  const renderer = useRenderer();
  const [local, initial] = splitProps(props, ["ref"]);
  const element = new DialogCloseRenderable(
    renderer,
    untrack(() => ({ ...initial, store })),
  );
  setRef(local.ref, element);
  let unregister: (() => void) | undefined;
  onMount(() => {
    let parent = element.parent;
    while (parent && !(parent instanceof DialogPopupRenderable)) {
      parent = parent.parent;
    }
    if (parent) unregister = parent.registerFocusable(element);
  });
  onCleanup(() => unregister?.());
  spreadProps(element, () => ({ ...initial }));
  return element;
}
export const DialogPrimitive = {
  Root,
  Trigger,
  Portal,
  Backdrop,
  Popup,
  Title,
  Description,
  Close,
} as const;

// packages/dialog/src/react-primitive.tsx
/** @jsxImportSource @opentui/react */

import { createPortal, extend, useRenderer } from "@opentui/react";
import {
  createContext,
  createElement,
  type ReactNode,
  type Ref,
  useCallback,
  useContext,
  useEffect,
  useLayoutEffect,
  useRef,
  useState,
  useSyncExternalStore,
} from "react";
import type { DialogPrimitiveState } from "./primitive/index";
import {
  DialogBackdropRenderable,
  type DialogCloseOptions,
  DialogCloseRenderable,
  type DialogDescriptionOptions,
  DialogDescriptionRenderable,
  type DialogPopupOptions,
  DialogPopupRenderable,
  type DialogPortalOptions,
  DialogPortalRenderable,
  type DialogRootOptions,
  DialogRootRenderable,
  DialogStore,
  type DialogTitleOptions,
  DialogTitleRenderable,
  type DialogTriggerOptions,
  DialogTriggerRenderable,
} from "./primitive/index";

const tags = {
  root: "otui-dialog-primitive-root",
  trigger: "otui-dialog-primitive-trigger",
  backdrop: "otui-dialog-primitive-backdrop",
  popup: "otui-dialog-primitive-popup",
  title: "otui-dialog-primitive-title",
  description: "otui-dialog-primitive-description",
  close: "otui-dialog-primitive-close",
};
extend({
  [tags.root]: DialogRootRenderable,
  [tags.trigger]: DialogTriggerRenderable,
  [tags.backdrop]: DialogBackdropRenderable,
  [tags.popup]: DialogPopupRenderable,
  [tags.title]: DialogTitleRenderable,
  [tags.description]: DialogDescriptionRenderable,
  [tags.close]: DialogCloseRenderable,
});

const StoreContext = createContext<DialogStore | null>(null);
const PopupContext = createContext<DialogPopupRenderable | null>(null);
// biome-ignore lint/suspicious/noExplicitAny: intrinsic refs share React's ref union
type PartProps<T> = Omit<T, "store"> & { ref?: Ref<any>; children?: ReactNode };
export type DialogRootProps = Omit<DialogRootOptions, "store"> & {
  children?: ReactNode | ((state: DialogPrimitiveState) => ReactNode);
  ref?: Ref<DialogRootRenderable>;
};
export type DialogTriggerProps = PartProps<DialogTriggerOptions>;
export type DialogPortalProps = Omit<DialogPortalOptions, "store"> & {
  children?: ReactNode;
  ref?: Ref<DialogPortalRenderable>;
};
export type DialogBackdropProps = PartProps<
  ConstructorParameters<typeof DialogBackdropRenderable>[1]
>;
export type DialogPopupProps = Omit<DialogPopupOptions, "store"> & {
  children?: ReactNode;
  ref?: Ref<DialogPopupRenderable>;
};
export type DialogTitleProps = PartProps<DialogTitleOptions>;
export type DialogDescriptionProps = PartProps<DialogDescriptionOptions>;
export type DialogCloseProps = Omit<DialogCloseOptions, "store"> & {
  children?: ReactNode;
  ref?: Ref<DialogCloseRenderable>;
};

function setRef<T>(ref: Ref<T> | undefined, value: T | null): void {
  if (typeof ref === "function") ref(value);
  else if (ref) ref.current = value;
}

function Root({ children, ref, ...props }: DialogRootProps) {
  const renderer = useRenderer();
  const storeRef = useRef<DialogStore | null>(null);
  if (!storeRef.current) storeRef.current = new DialogStore(renderer, props);
  const store = storeRef.current;
  const state = useSyncExternalStore(
    (listener) => store.subscribe(listener),
    () => store.state,
    () => store.state,
  );
  useEffect(() => () => store.destroy(), [store]);
  const content = typeof children === "function" ? children(state) : children;
  return createElement(
    StoreContext.Provider,
    { value: store },
    createElement(tags.root, { ...props, store, ref }, content),
  );
}
function useStore(name: string): DialogStore {
  const store = useContext(StoreContext);
  if (!store)
    throw new Error(
      `DialogPrimitive.${name} must be rendered inside DialogPrimitive.Root`,
    );
  return store;
}
function Trigger({ children, ref, ...props }: DialogTriggerProps) {
  return createElement(
    tags.trigger,
    { ...props, store: useStore("Trigger"), ref },
    children,
  );
}
function Portal({ children, ref, ...props }: DialogPortalProps) {
  const renderer = useRenderer();
  const store = useStore("Portal");
  const [portal] = useState(
    () => new DialogPortalRenderable(renderer, { ...props, store }),
  );
  useEffect(() => {
    renderer.root.add(portal);
    return () => {
      if (!portal.isDestroyed && portal.parent) portal.parent.remove(portal);
      if (!portal.isDestroyed) portal.destroyRecursively();
    };
  }, [portal, renderer]);
  useEffect(() => {
    setRef(ref, portal);
    return () => setRef(ref, null);
  }, [portal, ref]);
  useLayoutEffect(() => {
    const {
      visible: _,
      zIndex: __,
      ...safeProps
    } = props as DialogPortalOptions & {
      visible?: unknown;
      zIndex?: unknown;
    };
    Object.assign(portal, safeProps);
  });
  return createPortal(children, portal, portal);
}
function Backdrop({ children, ref, ...props }: DialogBackdropProps) {
  return createElement(
    tags.backdrop,
    { ...props, store: useStore("Backdrop"), ref },
    children,
  );
}
function Popup({ children, ref, ...props }: DialogPopupProps) {
  const store = useStore("Popup");
  const [popup, setPopup] = useState<DialogPopupRenderable | null>(null);
  const popupRef = useCallback(
    (value: DialogPopupRenderable | null) => {
      setPopup((current) => (current === value ? current : value));
      setRef(ref, value);
    },
    [ref],
  );
  return createElement(
    PopupContext.Provider,
    { value: popup },
    createElement(tags.popup, { ...props, store, ref: popupRef }, children),
  );
}
function TextPart({
  tag,
  children,
  store,
  ...props
}: {
  tag: string;
  children?: ReactNode;
  store: DialogStore;
  [key: string]: unknown;
}) {
  return createElement(tag, { ...props, store }, children);
}
function Title({ children, ...props }: DialogTitleProps) {
  return (
    <TextPart tag={tags.title} store={useStore("Title")} {...props}>
      {children}
    </TextPart>
  );
}
function Description({ children, ...props }: DialogDescriptionProps) {
  return (
    <TextPart tag={tags.description} store={useStore("Description")} {...props}>
      {children}
    </TextPart>
  );
}
function Close({ children, ref, ...props }: DialogCloseProps) {
  const store = useStore("Close");
  const popup = useContext(PopupContext);
  const closeRef = useRef<DialogCloseRenderable | null>(null);
  const closeElementRef = useCallback(
    (value: DialogCloseRenderable | null) => {
      closeRef.current = value;
      setRef(ref, value);
    },
    [ref],
  );
  useEffect(() => {
    const close = closeRef.current;
    if (!popup || !close) return;
    return popup.registerFocusable(close);
  }, [popup]);
  return createElement(
    tags.close,
    { ...props, store, ref: closeElementRef },
    children,
  );
}
export const DialogPrimitive = {
  Root,
  Trigger,
  Portal,
  Backdrop,
  Popup,
  Title,
  Description,
  Close,
} as const;
