// packages/react/src/checkbox/primitive.ts
import { extend } from "@opentui/react";
import {
  type CheckboxIndicatorOptions,
  CheckboxIndicatorRenderable,
  type CheckboxRootOptions,
  CheckboxRootRenderable,
  type CheckboxState,
  CheckboxStore,
} from "@tuiparts/core/checkbox";
import {
  createContext,
  createElement,
  type ReactElement,
  type ReactNode,
  type Ref,
  useContext,
} from "react";
import { useCoreStore } from "../internal/use-core-store";

const ROOT_TAG = "otui-checkbox-root";
const INDICATOR_TAG = "otui-checkbox-indicator";

extend({
  [ROOT_TAG]: CheckboxRootRenderable,
  [INDICATOR_TAG]: CheckboxIndicatorRenderable,
});

const CheckboxContext = createContext<CheckboxStore | null>(null);

type RootProps = Omit<CheckboxRootOptions, "store"> & {
  children?: ReactNode | ((state: CheckboxState) => ReactNode);
  ref?: Ref<CheckboxRootRenderable>;
};

type IndicatorProps = Omit<CheckboxIndicatorOptions, "store"> & {
  children?: ReactNode;
  ref?: Ref<CheckboxIndicatorRenderable>;
};

export function Root({ children, ...props }: Root.Props): ReactElement {
  const [store, state] = useCoreStore<CheckboxState, CheckboxStore>(
    () => new CheckboxStore(props),
  );
  const content = typeof children === "function" ? children(state) : children;

  return createElement(
    CheckboxContext.Provider,
    { value: store },
    createElement(ROOT_TAG, { ...props, store }, content),
  );
}

export function Indicator({
  children,
  ...props
}: Indicator.Props): ReactElement {
  const store = useContext(CheckboxContext);
  if (!store) {
    throw new Error("Checkbox.Indicator must be rendered inside Checkbox.Root");
  }
  return createElement(INDICATOR_TAG, { ...props, store }, children);
}

Root.displayName = "Checkbox.Root";
Indicator.displayName = "Checkbox.Indicator";

export namespace Root {
  export type Props = RootProps;
  export type State = CheckboxState;
}

export namespace Indicator {
  export type Props = IndicatorProps;
}

// packages/solid/src/radio/primitive.ts
import type { JSX } from "@opentui/solid";
import { useRenderer } from "@opentui/solid";
import {
  type RadioIndicatorOptions,
  RadioIndicatorRenderable,
  type RadioRootOptions,
  RadioRootRenderable,
  type RadioState,
} from "@tuiparts/core/radio";
import {
  type RadioGroupChangeDetails,
  type RadioGroupOptions,
  RadioGroupRenderable,
  type RadioGroupState,
  RadioGroupStore,
  type RadioGroupValueChangeHandler,
} from "@tuiparts/core/radio-group";
import {
  createComponent,
  createContext,
  createEffect,
  type Ref,
  Show,
  splitProps,
  untrack,
  useContext,
} from "solid-js";
import {
  setRenderableRef,
  spreadRenderableProps,
} from "../internal/renderable-props";
import { createRenderableState } from "../internal/renderable-state";

const RadioGroupContext = createContext<RadioGroupStore>();
const RadioContext = createContext<RadioRootRenderable>();

type RadioGroupProps = Omit<RadioGroupOptions, "store"> & {
  children?: JSX.Element | ((state: RadioGroupState) => JSX.Element);
  ref?: Ref<RadioGroupRenderable>;
};

type RootProps = Omit<RadioRootOptions, "store"> & {
  children?: JSX.Element | ((state: RadioState) => JSX.Element);
  ref?: Ref<RadioRootRenderable>;
};

type IndicatorProps = Omit<RadioIndicatorOptions, "radio"> & {
  children?: JSX.Element;
  keepMounted?: boolean;
  ref?: Ref<RadioIndicatorRenderable>;
};

export function RadioGroup(props: RadioGroup.Props): JSX.Element {
  const renderer = useRenderer();
  const store = new RadioGroupStore({
    value: props.value,
    defaultValue: props.defaultValue,
    disabled: props.disabled,
    onValueChange: props.onValueChange,
  });
  const state = createRenderableState(store, store.state);
  const publicState: RadioGroupState = {
    get value() {
      return state().value;
    },
    get disabled() {
      return state().disabled;
    },
  };
  const [local, renderableProps] = splitProps(props, [
    "children",
    "defaultValue",
    "disabled",
    "onValueChange",
    "ref",
    "value",
  ]);
  const element = new RadioGroupRenderable(
    renderer,
    untrack(() => ({ ...renderableProps, store })),
  );
  createEffect(() => {
    element.value = local.value;
    element.disabled = local.disabled;
    element.onValueChange = local.onValueChange;
  });
  setRenderableRef(local.ref, element);

  return createComponent(RadioGroupContext.Provider, {
    value: store,
    get children() {
      const child = local.children;
      const children = typeof child === "function" ? child(publicState) : child;
      spreadRenderableProps(element, () => ({ ...renderableProps, children }));
      return element;
    },
  });
}

export function Root(props: Root.Props): JSX.Element {
  const renderer = useRenderer();
  const store = useContext(RadioGroupContext);
  if (!store) {
    throw new Error("Radio.Root must be rendered inside RadioGroup");
  }
  const [local, renderableProps] = splitProps(props, [
    "children",
    "disabled",
    "ref",
    "value",
  ]);
  const element = new RadioRootRenderable(
    renderer,
    untrack(() => ({
      ...renderableProps,
      store,
      value: local.value,
      disabled: local.disabled,
    })),
  );
  createEffect(() => {
    element.value = local.value;
    element.disabled = local.disabled;
  });
  const state = createRenderableState(element, element.getState());
  const publicState: RadioState = {
    get value() {
      return state().value;
    },
    get available() {
      return state().available;
    },
    get disabled() {
      return state().disabled;
    },
    get focused() {
      return state().focused;
    },
    get checked() {
      return state().checked;
    },
    get tabbable() {
      return state().tabbable;
    },
  };
  setRenderableRef(local.ref, element);

  return createComponent(RadioContext.Provider, {
    value: element,
    get children() {
      const child = local.children;
      const children = typeof child === "function" ? child(publicState) : child;
      spreadRenderableProps(element, () => ({ ...renderableProps, children }));
      return element;
    },
  });
}

export function Indicator(props: Indicator.Props): JSX.Element {
  const renderer = useRenderer();
  const item = useContext(RadioContext);
  if (!item) {
    throw new Error("Radio.Indicator must be rendered inside Radio.Root");
  }
  const state = createRenderableState(item, item.getState());
  const [local, renderableProps] = splitProps(props, [
    "children",
    "keepMounted",
    "ref",
  ]);

  return createComponent(Show, {
    keyed: true,
    get when() {
      return local.keepMounted || state().checked;
    },
    get children() {
      const element = new RadioIndicatorRenderable(
        renderer,
        untrack(() => ({ ...renderableProps, radio: item })),
      );
      const children = local.children;
      setRenderableRef(local.ref, element);
      spreadRenderableProps(element, () => ({ ...renderableProps, children }));
      return element;
    },
  });
}

export namespace RadioGroup {
  export type Props = RadioGroupProps;
  export type State = RadioGroupState;
  export type ChangeDetails = RadioGroupChangeDetails;
  export type ValueChangeHandler = RadioGroupValueChangeHandler;
}

export namespace Root {
  export type Props = RootProps;
  export type State = RadioState;
}

export namespace Indicator {
  export type Props = IndicatorProps;
}
