// packages/solid/src/toggle-group/primitive.ts
import type { JSX } from "@opentui/solid";
import { useRenderer } from "@opentui/solid";
import {
  type ToggleGroupChangeDetails,
  type ToggleGroupOptions,
  type ToggleGroupOrientation,
  ToggleGroupRenderable,
  type ToggleGroupState,
  ToggleGroupStore,
  type ToggleGroupValueChangeHandler,
} from "@tuiparts/core/toggle-group";
import {
  createComponent,
  createEffect,
  type Ref,
  splitProps,
  untrack,
} from "solid-js";
import {
  setRenderableRef,
  spreadRenderableProps,
} from "../internal/renderable-props";
import { createRenderableState } from "../internal/renderable-state";
import { ToggleGroupContext } from "./context";

type ToggleGroupProps = Omit<ToggleGroupOptions, "store"> & {
  children?: JSX.Element | ((state: ToggleGroupState) => JSX.Element);
  ref?: Ref<ToggleGroupRenderable>;
};

/** Solid adapter for ToggleGroup selection and collection ownership. */
export function ToggleGroup(props: ToggleGroup.Props): JSX.Element {
  const renderer = useRenderer();
  const store = new ToggleGroupStore({
    defaultValue: props.defaultValue,
    disabled: props.disabled,
    loopFocus: props.loopFocus,
    multiple: props.multiple,
    onValueChange: props.onValueChange,
    orientation: props.orientation,
    value: props.value,
  });
  const state = createRenderableState(store, store.state);
  const publicState: ToggleGroupState = {
    get disabled() {
      return state().disabled;
    },
    get multiple() {
      return state().multiple;
    },
    get orientation() {
      return state().orientation;
    },
    get value() {
      return state().value;
    },
  };
  const [local, renderableProps] = splitProps(props, [
    "children",
    "defaultValue",
    "disabled",
    "loopFocus",
    "multiple",
    "onValueChange",
    "orientation",
    "ref",
    "value",
  ]);
  const element = new ToggleGroupRenderable(
    renderer,
    untrack(() => ({ ...renderableProps, store })),
  );
  createEffect(() => {
    element.disabled = local.disabled;
    element.loopFocus = local.loopFocus;
    element.multiple = local.multiple;
    element.onValueChange = local.onValueChange;
    element.orientation = local.orientation;
    element.value = local.value;
  });
  setRenderableRef(local.ref, element);

  return createComponent(ToggleGroupContext.Provider, {
    value: store,
    get children() {
      const child = local.children;
      const children = typeof child === "function" ? child(publicState) : child;
      spreadRenderableProps(element, () => ({ ...renderableProps, children }));
      return element;
    },
  });
}

/** Types scoped to the Solid ToggleGroup component. */
export namespace ToggleGroup {
  export type Props = ToggleGroupProps;
  export type State = ToggleGroupState;
  export type ChangeDetails = ToggleGroupChangeDetails;
  export type Orientation = ToggleGroupOrientation;
  export type ValueChangeHandler = ToggleGroupValueChangeHandler;
}

// packages/react/src/toggle-group/primitive.ts
import { extend } from "@opentui/react";
import {
  type ToggleGroupChangeDetails,
  type ToggleGroupOptions,
  type ToggleGroupOrientation,
  ToggleGroupRenderable,
  type ToggleGroupState,
  ToggleGroupStore,
  type ToggleGroupValueChangeHandler,
} from "@tuiparts/core/toggle-group";
import {
  createElement,
  type ReactElement,
  type ReactNode,
  type Ref,
} from "react";
import { useCoreStore } from "../internal/use-core-store";
import { ToggleGroupContext } from "./context";

const TOGGLE_GROUP_TAG = "otui-toggle-group";

extend({ [TOGGLE_GROUP_TAG]: ToggleGroupRenderable });

type ToggleGroupProps = Omit<ToggleGroupOptions, "store"> & {
  children?: ReactNode | ((state: ToggleGroupState) => ReactNode);
  ref?: Ref<ToggleGroupRenderable>;
};

/** React adapter for ToggleGroup selection and collection ownership. */
export function ToggleGroup({
  children,
  ...props
}: ToggleGroup.Props): ReactElement {
  const [store, state] = useCoreStore<ToggleGroupState, ToggleGroupStore>(
    () => new ToggleGroupStore(props),
  );
  const content = typeof children === "function" ? children(state) : children;
  return createElement(
    ToggleGroupContext.Provider,
    { value: store },
    createElement(TOGGLE_GROUP_TAG, { ...props, store }, content),
  );
}

ToggleGroup.displayName = "ToggleGroup";

/** Types scoped to the React ToggleGroup component. */
export namespace ToggleGroup {
  export type Props = ToggleGroupProps;
  export type State = ToggleGroupState;
  export type ChangeDetails = ToggleGroupChangeDetails;
  export type Orientation = ToggleGroupOrientation;
  export type ValueChangeHandler = ToggleGroupValueChangeHandler;
}
